package seeder

import (
	"database/sql"
	"log"
	"time"
	"tubeHunter/internal/model"
)

var Spots = []model.SpotDTO{
	{
		ID:          1,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Le petit Nice",
		City:        "La Teste-De-Buch",
		Country:     "France",
		Difficulty:  4,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          2,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Nazare",
		City:        "Nazaré",
		Country:     "Portugal",
		Difficulty:  5,
		SurfBreaks:  "Point Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          3,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Hossegor",
		City:        "Hossegor",
		Country:     "France",
		Difficulty:  4,
		SurfBreaks:  "Beach Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          4,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Pipeline",
		City:        "Oahu",
		Country:     "Hawaii",
		Difficulty:  5,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          5,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Jeffreys Bay",
		City:        "Jeffreys Bay",
		Country:     "South Africa",
		Difficulty:  3,
		SurfBreaks:  "Point Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          6,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Mavericks",
		City:        "Mavericks",
		Country:     "USA",
		Difficulty:  5,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          7,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Teahupo’o",
		City:        "Teahupo’o",
		Country:     "Tahiti",
		Difficulty:  5,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          8,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Banzai Pipeline",
		City:        "Banzai Pipeline",
		Country:     "Hawaii",
		Difficulty:  5,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          9,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Uluwatu",
		City:        "Uluwatu",
		Country:     "Indonesia",
		Difficulty:  4,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          10,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Bondi Beach",
		City:        "Bondi Beach",
		Country:     "Australia",
		Difficulty:  3,
		SurfBreaks:  "Beach Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          11,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Snapper Rocks",
		City:        "Snapper Rocks",
		Country:     "Australia",
		Difficulty:  3,
		SurfBreaks:  "Point Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          12,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Waimea Bay",
		City:        "Waimea Bay",
		Country:     "Hawaii",
		Difficulty:  4,
		SurfBreaks:  "Big Wave",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          13,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Raglan",
		City:        "Raglan",
		Country:     "New Zealand",
		Difficulty:  3,
		SurfBreaks:  "Point Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          14,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Teahupo’o Left",
		City:        "Teahupo’o Left",
		Country:     "Tahiti",
		Difficulty:  5,
		SurfBreaks:  "Reef Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          15,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Puerto Escondido",
		City:        "Puerto Escondido",
		Country:     "Mexico",
		Difficulty:  4,
		SurfBreaks:  "Beach Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          16,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Fistral Beach",
		City:        "Fistral Beach",
		Country:     "UK",
		Difficulty:  3,
		SurfBreaks:  "Beach Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          17,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Bells Beach",
		City:        "Bells Beach",
		Country:     "Australia",
		Difficulty:  4,
		SurfBreaks:  "Point Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          18,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Canggu",
		City:        "Canggu",
		Country:     "Indonesia",
		Difficulty:  3,
		SurfBreaks:  "Beach Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          19,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "Rincon",
		City:        "Rincon",
		Country:     "Puerto Rico",
		Difficulty:  3,
		SurfBreaks:  "Point Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
	{
		ID:          20,
		PhotoURL:    "https://res.cloudinary.com/manawa/image/private/f_auto,c_limit,w_3840,q_auto/aykvlohikeutpdcp720o",
		Name:        "El Sunzal",
		City:        "El Sunzal",
		Country:     "El Salvador",
		Difficulty:  2,
		SurfBreaks:  "Beach Break",
		SeasonStart: time.Date(2025, time.March, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
		SeasonEnd:   time.Date(2025, time.November, 30, 0, 0, 0, 0, time.UTC).Format("2006-01-02"),
	},
}

func SeedSpots(db *sql.DB) {
	for _, s := range Spots {
		_, err := db.Exec(
			"INSERT OR IGNORE INTO spots (id, photo_url, name, city, country, difficulty, surf_breaks, season_start, season_end) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
			s.ID, s.PhotoURL, s.Name, s.City, s.Country, s.Difficulty, s.SurfBreaks, s.SeasonStart, s.SeasonEnd,
		)
		if err != nil {
			log.Printf("⚠️ Erreur seed spot %s: %v", s.Name, err)
		}
	}
	log.Println("✅ Seeder executed")
}
